# Generated by Django 5.2.1 on 2025-05-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NatoMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('joined_year', models.IntegerField()),
                ('continent', models.CharField(max_length=100)),
                ('capital_city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'natomember',
                'ordering': ['joined_year'],
            },
        ),
    ]
