# Generated by Django 5.2.1 on 2025-05-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='natomember',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
