# Generated by Django 5.2.1 on 2025-05-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nato', '0002_natomember_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natomember',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
